version: "3.5"
services:
  develop:
    build: .
    container_name: fw-teams-develop
    ports:
        - "3035:3035"
    environment:
      NODE_ENV: dev
      SUPPRESS_NO_CONFIG_WARNING: "true"
      LOGGER_LEVEL: debug
      SERVICE_PORT: 3035
      JWT_SECRET: reallyunguessablesecretkey
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      DB_SECRET: '{ "username": "admin", "password": "password" }'
      DB_DATABASE: fw_teams_db
      REDIS_URL: redis://redis:6379
      REDIS_QUEUE_NAME: mail
      APP_URL: http://127.0.0.1:3035
      USERS_API_URL: https://api.resourcewatch.org
      CONTROL_TOWER_URL: https://api.resourcewatch.org
    volumes:
      - ./app:/opt/fw-teams/app
      - ./nodemon.json:/opt/fw-teams/nodemon.json
    depends_on:
      - mongo
      - redis
    networks:
      - gfw-teams-network
      - gfw-network
    command: yarn dev

  test:
    build: .
    container_name: fw-teams-test
    environment:
      PORT: 0
      NODE_ENV: test
      SUPPRESS_NO_CONFIG_WARNING: "true"
      LOGGER_LEVEL: debug
      SERVICE_PORT: 3035
      JWT_SECRET: reallyunguessablesecretkey
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      DB_SECRET: '{ "username": "admin", "password": "password" }'
      DB_DATABASE: fw_teams_db
      REDIS_URL: redis://redis:6379
      REDIS_QUEUE_NAME: mail
      APP_URL: http://127.0.0.1:3035
      USERS_API_URL: http://127.0.0.1:9000
      CONTROL_TOWER_URL: http://127.0.0.1:9000
    depends_on:
      - mongo
      - redis
    volumes:
      - ./app:/opt/fw-teams/app
      - ./nodemon.json:/opt/fw-teams/nodemon.json
      - ./jest.config.js:/opt/fw-teams/jest.config.js
    command: yarn test

  docs:
    build: .
    ports:
      - "30350:30350"
    container_name: fw-teams-docs
    volumes:
      - ./docs:/opt/fw-teams/docs
    command: yarn run docs -l 30350

  mongo:
    image: mongo:3.4
    container_name: fw-teams-mongo-develop
    ports:
      - "27022:27017"
    environment:
      MONGO_INITDB_DATABASE: fw_teams_db
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: admin
    volumes:
      - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - fw-teams-mongodb-data:/data/db
    restart: always
    networks:
      - gfw-network

  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - gfw-teams-network

volumes:
  fw-teams-mongodb-data:

networks:
  gfw-teams-network:
    name: gfw-teams-network
  gfw-network:
    name: gfw-network

