version: "3.5"
services:
  develop:
    build: .
    container_name: fw-teams-develop
    ports:
        - "3035:3035"
    environment:
      NODE_PATH: app/src
      NODE_ENV: dev
      SUPPRESS_NO_CONFIG_WARNING: "true"
      LOGGER_LEVEL: debug
      SERVICE_PORT: 3035
      JWT_SECRET: reallyunguessablesecretkey
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      REDIS_URL: redis://redis:6379
      REDIS_QUEUE_NAME: mail
      APP_URL: http://127.0.0.1:3035
      USERS_API_URL: https://api.resourcewatch.org
      CONTROL_TOWER_URL: https://api.resourcewatch.org
    volumes:
      - ./app:/opt/fw-teams/app
      - ./config:/opt/fw-teams/config
      - ./node_modules:/opt/fw-teams/node_modules
      - ./package.json:/opt/fw-teams/package.json
      - ./yarn.lock:/opt/fw-teams/yarn.lock
    depends_on:
      - mongo
      - redis
    networks:
      - gfw-teams-network
      - gfw-network
    command: sh -c "yarn install && node node_modules/.bin/grunt --gruntfile app/Gruntfile.js"

  mongo:
    image: mongo:3.4
    container_name: fw-teams-mongo-develop
    ports:
      - "27022:27017"
    volumes:
      - $HOME/docker/data/fw-teams/mongodb:/data/db
    restart: always
    networks:
      - gfw-network

  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - gfw-teams-network
networks:
  gfw-teams-network:
    name: gfw-teams-network
  gfw-network:
    name: gfw-network

