version: "3"
services:
  test:
    build: .
    ports:
      - "3035:3035"
    container_name: fw-teams-test
    environment:
      PORT: 3035
      NODE_PATH: app/src
      NODE_ENV: test
      CT_URL: http://127.0.0.1:9000
      LOCAL_URL: http://127.0.0.1:3035
      USER_API_URL: http://127.0.0.1:9000
      MONGO_PORT_27017_TCP_ADDR: mongo
      REDIS_PORT_6379_TCP_ADDR: redis
      JWT_SECRET: reallyunguessablesecretkey
      API_VERSION: v1
      API_GATEWAY_URL: http://127.0.0.1:9000
      API_GATEWAY_EXTERNAL_URL: http://127.0.0.1:9000
      API_GATEWAY_QUEUE_URL: redis://redis:6379
      API_GATEWAY_QUEUE_NAME: mail
      APP_URL: http://127.0.0.1:3035
    command: test
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:3.4
    command: --smallfiles
    ports:
      - "27017"

  redis:
    image: bitnami/redis
    ports:
      - "6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
