version: "3.5"
services:
  develop:
    build: .
    container_name: fw-teams-develop
    ports:
        - "3035:3035"
    environment:
      PORT: 3035
      NODE_PATH: app/src
      CT_URL: https://api.resourcewatch.org
      LOCAL_URL: http://127.0.0.1:3035
      USER_API_URL: https://api.resourcewatch.org
      MONGO_PORT_27017_TCP_ADDR: mongo
      REDIS_PORT_6379_TCP_ADDR: redis
      JWT_SECRET: reallyunguessablesecretkey
      API_VERSION: v1
      API_GATEWAY_URL: http://127.0.0.1:9000
      API_GATEWAY_EXTERNAL_URL: http://127.0.0.1:9000
      API_GATEWAY_QUEUE_URL: redis://redis:6379
      API_GATEWAY_QUEUE_NAME: mail
      APP_URL: http://127.0.0.1:3035
      FASTLY_ENABLED: "false"
    command: develop
    volumes:
      - ./app:/opt/fw-teams/app
    depends_on:
      - mongo
      - redis
    networks:
      - gfw-teams-network
      - gfw-network

  mongo:
    image: mongo:3.4
    container_name: fw-teams-mongo-develop
    ports:
      - "27022:27017"
    volumes:
      - $HOME/docker/data/fw-teams/mongodb:/data/db
    restart: always
    networks:
      - gfw-network

  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - gfw-teams-network
networks:
  gfw-teams-network:
    name: gfw-teams-network
  gfw-network:
    name: gfw-network

