version: "3"
services:
  test:
    build: .
    ports:
      - "3035:3035"
    container_name: fw-teams-test
    environment:
      NODE_PATH: app/src
      NODE_ENV: test
      SUPPRESS_NO_CONFIG_WARNING: "true"
      LOGGER_LEVEL: debug
      SERVICE_PORT: 3035
      JWT_SECRET: reallyunguessablesecretkey
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      REDIS_URL: redis://redis:6379
      REDIS_QUEUE_NAME: mail
      APP_URL: http://127.0.0.1:3035
      USERS_API_URL: http://127.0.0.1:9000
      CONTROL_TOWER_URL: http://127.0.0.1:9000
    depends_on:
      - mongo
      - redis
    command: node node_modules/.bin/grunt --gruntfile app/Gruntfile.js e2eTest

  mongo:
    image: mongo:3.4
    command: --smallfiles
    ports:
      - "27017"

  redis:
    image: bitnami/redis
    ports:
      - "6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
