name: eslint

on: [push]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Start containers
      run: docker-compose -f "docker-compose-develop.yml" up -d --build

    - name: Run eslint
      run : docker-compose -f "docker-compose-develop.yml" run develop yarn run prettier:check

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose-develop.yml" down